"""empty message

Revision ID: 8c6256bf06cb
Revises: bc0779da003e
Create Date: 2023-05-30 02:56:38.669740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6256bf06cb'
down_revision = 'bc0779da003e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocked_list', schema=None) as batch_op:
        batch_op.alter_column('jti',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocked_list', schema=None) as batch_op:
        batch_op.alter_column('jti',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
